name: Request Unity License
on:
  workflow_dispatch:

jobs:
  requestLicense:
    runs-on: ubuntu-latest
    steps:
      - name: Request license
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2023.1.0f1
      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: UnityActivationFile
          path: Unity_v2023.1.0f1.alf
